<?php 
/**
	Admin Page Framework v3.8.15 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/shellpress>
	Copyright (c) 2013-2017, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class SP_v1_0_8_AdminPageFramework_FieldType__nested extends SP_v1_0_8_AdminPageFramework_FieldType {
    public $aFieldTypeSlugs = array('_nested');
    protected $aDefaultKeys = array();
    protected function getStyles() {
        return ".shellpress-fieldset > .shellpress-fields > .shellpress-field.with-nested-fields > .shellpress-fieldset.multiple-nesting {margin-left: 2em;}.shellpress-fieldset > .shellpress-fields > .shellpress-field.with-nested-fields > .shellpress-fieldset {margin-bottom: 1em;}.with-nested-fields > .shellpress-fieldset.child-fieldset > .shellpress-child-field-title {display: inline-block;padding: 0 0 0.4em 0;}.shellpress-fieldset.child-fieldset > label.shellpress-child-field-title {display: table-row; white-space: nowrap;}";
    }
    protected function getField($aField) {
        $_oCallerForm = $aField['_caller_object'];
        $_aInlineMixedOutput = array();
        foreach ($this->getAsArray($aField['content']) as $_aChildFieldset) {
            if (is_scalar($_aChildFieldset)) {
                continue;
            }
            if (!$this->isNormalPlacement($_aChildFieldset)) {
                continue;
            }
            $_aChildFieldset = $this->getFieldsetReformattedBySubFieldIndex($_aChildFieldset, ( integer )$aField['_index'], $aField['_is_multiple_fields'], $aField);
            $_oFieldset = new SP_v1_0_8_AdminPageFramework_Form_View___Fieldset($_aChildFieldset, $_oCallerForm->aSavedData, $_oCallerForm->getFieldErrors(), $_oCallerForm->aFieldTypeDefinitions, $_oCallerForm->oMsg, $_oCallerForm->aCallbacks);
            $_aInlineMixedOutput[] = $_oFieldset->get();
        }
        return implode('', $_aInlineMixedOutput);
    }
}
class SP_v1_0_8_AdminPageFramework_FieldType_inline_mixed extends SP_v1_0_8_AdminPageFramework_FieldType__nested {
    public $aFieldTypeSlugs = array('inline_mixed');
    protected $aDefaultKeys = array('label_min_width' => '', 'show_debug_info' => false,);
    protected function getStyles() {
        return ".shellpress-field-inline_mixed {width: 98%;}.shellpress-field-inline_mixed > fieldset {display: inline-block;overflow-x: visible;padding-right: 0.4em;}.shellpress-field-inline_mixed > fieldset > .shellpress-fields{display: inline;width: auto;table-layout: auto;margin: 0;padding: 0;vertical-align: middle;white-space: nowrap;}.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field {float: none;clear: none;width: 100%;display: inline-block;margin-right: auto;vertical-align: middle; }.with-mixed-fields > fieldset > label {width: auto;padding: 0;}.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field .shellpress-input-label-string {padding: 0;}.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field > .shellpress-input-label-container,.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field > * > .shellpress-input-label-container{padding: 0;display: inline-block;width: 100%;}.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field > .shellpress-input-label-container > label,.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field > * > .shellpress-input-label-container > label{display: inline-block;}.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field > .shellpress-input-label-container > label > input,.shellpress-field-inline_mixed > fieldset > .shellpress-fields > .shellpress-field > * > .shellpress-input-label-container > label > input{display: inline-block;min-width: 100%;margin-right: auto;margin-left: auto;}.shellpress-field-inline_mixed .shellpress-input-label-container,.shellpress-field-inline_mixed .shellpress-input-label-string{min-width: 0;}";
    }
}
