<?php 
/**
	Admin Page Framework v3.8.15 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/shellpress>
	Copyright (c) 2013-2017, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class SP_v1_0_8_AdminPageFramework_Form_View___Script_OptionStorage extends SP_v1_0_8_AdminPageFramework_Form_View___Script_Base {
    static public function getScript() {
        return <<<JAVASCRIPTS
(function ( $ ) {
            
    $.fn.aSP_v1_0_8_AdminPageFrameworkInputOptions = {}; 
                            
    $.fn.storeSP_v1_0_8_AdminPageFrameworkInputOptions = function( sID, vOptions ) {
        var sID = sID.replace( /__\d+_/, '___' );	// remove the section index. The g modifier is not used so it will replace only the first occurrence.
        $.fn.aSP_v1_0_8_AdminPageFrameworkInputOptions[ sID ] = vOptions;
    };	
    $.fn.getSP_v1_0_8_AdminPageFrameworkInputOptions = function( sID ) {
        var sID = sID.replace( /__\d+_/, '___' ); // remove the section index
        return ( 'undefined' === typeof $.fn.aSP_v1_0_8_AdminPageFrameworkInputOptions[ sID ] )
            ? null
            : $.fn.aSP_v1_0_8_AdminPageFrameworkInputOptions[ sID ];
    }

}( jQuery ));
JAVASCRIPTS;
        
    }
}
