<?php 
/**
	Admin Page Framework v3.8.15 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/shellpress>
	Copyright (c) 2013-2017, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class SP_v1_0_6_AdminPageFramework_Form_View___CSS_Form extends SP_v1_0_6_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        $_sSpinnerURL = esc_url(admin_url('/images/wpspin_light-2x.gif'));
        return ".shellpress-form-warning {font-size: 1em;}";
    }
}
