<?php 
/**
	Admin Page Framework v3.8.15 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/shellpress>
	Copyright (c) 2013-2017, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class SP_v1_0_6_AdminPageFramework_Form_View___CSS_term_meta extends SP_v1_0_6_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".shellpress-form-table-outer-row-term_meta,.shellpress-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.shellpress-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.shellpress-form-table-term_meta .shellpress-sectionset,.shellpress-form-table-term_meta .shellpress-section {margin-bottom: 0;}.shellpress-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.shellpress-form-table-term_meta.add-new-term .shellpress-section .form-table > tbody > tr > td,.shellpress-form-table-term_meta.add-new-term .shellpress-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.shellpress-form-table-term_meta.add-new-term .shellpress-field {width: auto;}.shellpress-form-table-term_meta.add-new-term .shellpress-field {max-width: 100%;}.shellpress-form-table-term_meta.add-new-term .sortable .shellpress-field {width: auto;} .shellpress-form-table-term_meta.add-new-term .shellpress-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.shellpress-form-table-term_meta .shellpress-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.shellpress-form-table-term_meta .shellpress-collapsible-title h3 {margin: 0;}.shellpress-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.shellpress-form-table-term_meta .shellpress-section-tab h4 {margin: 0;} ";
    }
}
